language: d
d:
  - dmd
env:
  global:
    - PATH=${PATH}:${TRAVIS_BUILD_DIR}/make
script:
 - mkdir -p make && cd make && curl -L http://ftp.gnu.org/gnu/make/make-4.1.tar.gz  | tar -zxf - --strip-components=1 && ./configure && make && ./make -v
 - make -v
 - make -f posix.mak all
